### ISSUE TITLE
No Documentation for State Machine API

### ISSUE THREAD

**Issue by GaganBhat** [team401/SnakeSkin#10]
I was reading through the GitBooks when I realized that there was no documentation on one of the pages. We look forward to using SnakeSkin as the base for next year, so we were wondering if this could possibly be filled in. 

https://team401.gitbooks.io/snakeskin/content/api-documentation/state-machine.html

**Comment by PChild** [comment]
@GaganBhat We will be working on documentation and expanding the feature set in the offseason. Until we have time to improve documentation you can always check out how we use it in our [2018 robot code](https://github.com/team401/2018-Robot-Code).

**Comment by camearle20** [comment]
Just to update this thread, I've been working on documentation recently, and we should have most of the features documented before the 2019 build season starts.

**Comment by PChild** [comment]
The Gitbook is updated with new docs, and there are javadocs for all of the modules linked in the readme. Closing this issue out for now.
