### ISSUE TITLE
Remove old Unit file?

### ISSUE THREAD

**Issue by PChild** [team401/SnakeSkin#14]
Can we remove the old [Unit]( https://github.com/team401/SnakeSkin/blob/2f939d67bdc2c812cf3985815859371823afd8c9/SnakeSkin-Core/src/main/kotlin/org/snakeskin/Unit.kt) file now that [Units](https://github.com/team401/SnakeSkin/tree/2f939d67bdc2c812cf3985815859371823afd8c9/SnakeSkin-Core/src/main/kotlin/org/snakeskin/units) are coming in?

**Comment by camearle20** [comment]
Yes, this will be removed next commit
