### ISSUE TITLE
Move units from buildSrc to a composite build

### ISSUE THREAD

**Issue by PChild** [team401/SnakeSkin#16]
Having the units stuff in buildSrc is a bit unintuitive, [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) replicate the buildSrc functionality and would allow us to provide a meaningful name such as SnakeSkin-Units.

See example: https://github.com/gradle/gradle/issues/2472#issuecomment-315376378

**Comment by camearle20** [comment]
Denied.

**Comment by PChild** [comment]
Closing issue, units moved to [SnakeSkin-Units](https://github.com/team401/SnakeSkin-Units).
