### ISSUE TITLE
Migrate Robot.java to Kotlin

### ISSUE THREAD

**Issue by PChild** [team401/SnakeSkin#5]
I don't think it makes sense to have a single java file in an entirely kotlin based project. Can we at least test with migrating to a Robot.kt?

**Comment by camearle20** [comment]
No.

**Comment by PChild** [comment]
Reopening for testing! 👍

**Comment by camearle20** [comment]
Feature is done! Closing!

**Comment by PChild** [comment]
Closed by latest commit. :-)

**Comment by PChild** [comment]
Given GradleRIO's  Kotlin robot example, can we actually do this now?

**Comment by PChild** [comment]
Bump.
